global:
  base_port: 5555            # Cam1→5555, Cam2→5556
  jpeg_quality: 80
  send_intrinsics: true
  align_to_color: true
  preview: false             # set true for quick OpenCV windows
  pose_dir: ./poses
  depth_min_mm: 400
  depth_max_mm: 6000
  roi_xywh: [160, 90, 960, 540]
  downsample_stride: 3           # 1=no DS, 2=quarter pixels, 3≈1/9th
  median_ksize: 3                 # optional denoise; 0 disables

cameras:
  - id: 1
    type: azure
    device: 0
    port: 5555
    color_res: [1280, 720]
    pose_file: "C:/Users/yadhu/PointsPublisher/poses/cam1_Twc.txt"

  - id: 2
    type: azure
    device: 1
    port: 5556
    color_res: [1280, 720]
    pose_file: "C:/Users/yadhu/PointsPublisher/poses/cam2_Twc.txt"
